target 'HomeFrame' do
    platform :ios, '8.0'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'Masonry', '~> 1.0.2'
    pod 'FMDB', '~> 2.7.2'
    pod 'SDWebImage', '~> 4.1.0'
    pod 'IQKeyboardManager', '~> 4.0.11'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'MJExtension', '~> 3.0.13'
    pod 'XJKAlertView', '~> 1.0'
end
